name: update-algolia-index
run-name: ${{ github.actor }} update algolia indexes
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    env:
      ALGOLIA_API_KEY_ADMIN: ${{ secrets.ALGOLIA_API_KEY_ADMIN }}
      PUSH_GITHUB_API: ${{ secrets.PUSH_GITHUB_API }}
      NEXT_PUBLIC_ALGOLIA_APP_ID: L00HP1BY6T
      NEXT_PUBLIC_ALGOLIA_INDEX_NAME: posts
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      - run: yarn
      - run: node ./lib/sendToAlgolia.js
      - run: sh ./scripts/commitAndPush.sh
